---
title: "Pixel Perfect"
author: "L8rhosen"
date: "2025-07-06"
description: "You are trying to hard."
categories: [rants]
---

To all gamers, game designers, streamers.... you are trying too hard.

I recently upgraded to a new big ultra widescreen monitor.  I was a little worried about switch from 4k to a slightly less dense resolution.
My gaming rig is a NUC with mobile GPU.. so pushing that big a monitor, I've had to turn down the graphics on all the shooter games at least.  And of course, I can't tell a fucking difference.  Games are smooth as shit.. and while I'm smoking pukes and rolling through the map I can't tell one bit that the graphics are "_low resolution_".

If you think I'm wrong.. 1) I don't care and 2) You are fooling yourself.

You don't need a $800 GPU to make these games as fun as always.  None of you are playing a shooter game and looking at the grass textures thinking it's not "realistic" enough.  Hell, your character is a fucking ninja turtle wearing superman's cape holding a lightsaber .. doing a Rick Roll dance.  

Framerates and smooth animations are what make these games enjoyable.

Now move to a RTS or adventure game, etc.. crank up the visuals and turn down the performance, you don't need it.  

Stop trying so hard.

End of line.