project:
  type: website
  resources: 
    - "CNAME"

website:
  title: "L8rhosen dot com"
  site-url: https://www.l8rhosen.com
  favicon: CODProfile.jpg
  navbar:
    right:
      - about.qmd
  open-graph:
    site-name: L8rhosen
  google-analytics: G-JJJJG6SFGC

format:
  html:
    theme: superhero
    css: styles.css

execute:
  freeze: auto

editor:
  markdown: 
    canonical: true


