project:
  type: website

website:
  title: "L8rhosen dot com"
  favicon: CODProfile.jpg
  navbar:
    right:
      - about.qmd
format:
  html:
    theme: superhero
    css: styles.css

execute:
  freeze: auto


